name: hamrobhumi
description: A new Flutter project.

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  url_launcher: "^3.0.2"
  material_search: "^0.2.7"
  video_player: "^0.6.0"
  flutter_staggered_grid_view: ^0.2.7


dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
  assets:
    - static/images/logo.png
    - static/images/area.jpg
    - static/images/length.jpg
    - static/images/plotter.jpg
    - static/json/menu_item.json
    - static/json/news/news.json
    - static/json/download/tab1.json
    - static/json/download/tab2.json
    - static/json/download/tab3.json
    - static/json/download/tab4.json
    - static/images/placeholder.png
    - static/icons/mainservices.png
    - static/icons/calculator.png
    - static/icons/dictionary.png
    - static/icons/download.png
    - static/icons/citizencharter.png
    - static/icons/priorityprojects.png
    - static/icons/feedback.png
    - static/icons/video.png
    - static/icons/sampleform.png
    - static/icons/faq.png
    - static/icons/map.png
    - static/icons/news.png
    - static/icons/minister.jpg
    - static/icons/service.png
    - static/icons/information_section.png
    - static/video/introvideo.mp4
    - static/icons/draw_measure.png
    - static/icons/unit_conversion.png
    - static/icons/tax_rate.png
    - static/icons/capital_tax_rate.png
    - static/icons/capital_tax_rate.png
    - static/icons/local_unit_maps_new.png
    - static/icons/find_your_office.png
    - static/icons/information_section_new.png
    - static/icons/main_services_new.png
    - static/icons/office_details_new.png
    - static/icons/faq_new.png
    - static/icons/instagram.png
    - static/icons/download_new.png
    - static/icons/twitter.png
    - static/icons/facebook.png







  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
